### ISSUE TITLE
To-do list 2020-06

### ISSUE THREAD

**Issue by shanmdphd** [rbind/shanmdphd.rbind.io#1]
I would like to write several things to do here.

**Comment by shanmdphd** [comment]
# 2020-06-24

- [x] pipet.or.kr/books - commit update
- [x] pipetapps.com - upgrade to R 4.0.1
- [x] Submission to DDDT (1.0 hr)
- [ ] Dallphin - Manual (1.0 hr)
- [ ] Tiumbio - Responses (0.5 hr)
- [ ] Scoring - CPT (M3) (1.0 hr)
